name: 'Test minimal_example.Rmd'
description: 'Run tests for minimal_example.Rmd'
runs:
  using: "composite"
  steps:
    - id: knit-reports
      run: |
        Rscript -e 'rmarkdown::render("minimal_example.Rmd", params = list(some_value = 1), output_file = "minimal_numeric_1.html")'
        Rscript -e 'rmarkdown::render("minimal_example.Rmd", params = list(some_value = "1"), output_file = "minimal_character_1.html")'
        Rscript -e 'rmarkdown::render("minimal_example.Rmd", output_file = "minimal_null.html")'
      shell: bash
    - id: test-report-content
      run: poetry run python ./.github/actions/test-minimal-rmd/soup_tests.py
      shell: bash