name: rmd knit tests

on: [ push ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: r-setup
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.2.0
      - name: install-dependencies
        run: |
          Rscript -e 'install.packages("rmarkdown")'
      - name: simple-knit
        run: |
          Rscript -e 'rmarkdown::render("minimal_example.Rmd", params = list(some_number = 1))'
      - name: upload-outputs
        uses: actions/upload-artifact@v3
        with:
          name: html-reports
          path: ./*.html
