name: rmd knit tests

on: [ push ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: r-setup
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.2.0
      - name: install-dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
          Rscript -e 'install.packages(c("rmarkdown", "flexdashboard"))'
      - name: simple-knit
        uses: test-minimal-rmd
      - name: upload-outputs
        uses: actions/upload-artifact@v3
        with:
          name: html-reports
          path: ./*.html
